<?php

declare(strict_types=1);

namespace Juling\DevTools\Resolvers;

use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Juling\DevTools\Support\DevConfig;
use Juling\DevTools\Support\SchemaTrait;
use ReflectionClass;
use ReflectionException;
use ReflectionMethod;

class ModulePageRouteResolver extends Foundation
{
    use SchemaTrait;

    /**
     * @throws ReflectionException
     */
    public function build(DevConfig $devConfig, array $data): void
    {
        $modules = glob(app_path('Modules/*'), GLOB_ONLYDIR);
        foreach ($modules as $modulePath) {
            $dist = $modulePath.'/Routes';
            $this->ensureDirectoryExists($dist);

            $moduleName = basename($modulePath);
            $routes = $this->getViewRoutes($moduleName, $modulePath);

            file_put_contents($dist.'/web.php', $this->getTemplate($routes));
        }
    }

    private function getViewRoutes(string $module, string $modulePath): string
    {
        $module = Str::lower($module);

        $exclude = config('devtools.exclude_views');
        $routeContent = '// Route start';
        $routeContent .= "\nRoute::prefix('{$module}')->middleware('web')->name('{$module}.')->group(function () {";

        $files = File::allFiles($modulePath.'/Pages');
        foreach ($files as $file) {
            $view = Str::replace('\\', '/', $file->getPathname());
            preg_match('/Pages\/(.+?)\.blade\.php/', $view, $matches);
            if (isset($matches[1])) {
                $routePath = $matches[1];
                $routeName = Str::replace('/', '.', $routePath);
                $routeView = $module.'Pages::'.$routeName;
                if (in_array($routePath, $exclude) || str_contains($routePath, 'layouts')) {
                    continue;
                }
                if (Str::substr($routePath, -6) === '/index') {
                    $routePath = Str::substr($routePath, 0, -6);
                } elseif ($routePath === 'index') {
                    $routePath = '/';
                }
                $routeContent .= "\n    Route::view('{$routePath}', '{$routeView}')->name('{$routeName}');";
            }
        }
        $routeContent .= "\n});";
        $routeContent .= "\n// end";

        return $routeContent;
    }

    private function getTemplate($content): string
    {
        return <<<EOF
<?php

// ==========================================================================
// Code generated by gen:module:page:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

$content

EOF;
    }
}
